# Generated by Django 2.2.15 on 2020-08-31 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('regular', 'regular')], max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is User Active')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2020, 8, 31, 8, 29, 34, 783048, tzinfo=utc), verbose_name='Date Joined')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
