# Generated by Django 2.2.16 on 2020-09-02 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 6, 29, 2, 9914, tzinfo=utc), verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Phone number with country code', max_length=128, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
