# Generated by Django 2.2.16 on 2020-09-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200902_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Joined'),
        ),
    ]
